name: Build

on: push

permissions:
  contents: write # Upload artifacts to release
  id-token: write # Use PyPI trusted publishing

jobs:
  build:
    name: Build and Inspect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v2

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: pypi
      url: https://pypi.org/p/meltano-tap-circle-ci
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4.1.2
        with:
          name: Packages
          path: dist
      - name: Upload wheel to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.whl
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.8.11
